services:
  mcp-server:
    build:
      context: ./mcp_server
    expose:
      - "8000"

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; r=urllib.request.urlopen('http://localhost:8000/health'); assert r.status == 200",
        ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  agent:
    build:
      context: ./agent
    depends_on:
      mcp-server:
          condition: service_healthy
    environment:
      MCP_SERVER_URL: http://mcp-server:8000/mcp
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    stdin_open: true
    tty: true